trigger:
- main

pool:
  name: Default

steps:
- task: PowerShell@2
  displayName: 'Deploy Stored Procedure'
  inputs:
    targetType: 'inline'
    script: |
      sqlcmd -S THANASEKAR -d AdventureWorks2022 -E -i procedures/uspGetBillOfMaterials.sql
